package eecs2030.pe2;

import eecs2030.pe2.CallZone;

/**
* A class that specifies a telephone call to a particular phone number
* in a particular call zone for a particular number of minutes.
* 
* @author EECS2030
*
*/
public class Call
{
	private String number;
	private CallZone zone;
	private int minutes;

	/**
	 * Create a call with the given number, call zone, and number of minutes.
	 * 
	 * @param number the call's number.
	 * @param zone the call's call zone.
	 * @param minutes the call's duration in minutes.
	 * @pre. minutes is positive and number and zone are not null.
	 */
	public Call(String number, CallZone zone, int minutes)
	{
		assert(minutes > 0);
		this.setNumber(number);
		this.setZone(zone);
		this.setMinutes(minutes);
	}

	/**
	 * Make a copy of the given call.
	 * 
     * @param call the call to make a copy of.
     * @pre. call is not null.
	 */
	public Call(Call call)
	{
		this(call.getNumber(),call.getZone(),call.getMinutes());
	}

	/**
	 * Get the number of this call.
	 * 
	 * @return the number of this call.
	 */
	public String getNumber()
	{
		return this.number;
	}
	
	/**
	 * Set the number of this call.
	 * 
	 * @param number the number to set.
	 * @pre. number is not null.
	 */
	public void setNumber(String number)
	{
		this.number = number;
	}
	
	/**
	 * Get the zone of this call.
	 * 
	 * @return the zone of this call.
	 */
	public CallZone getZone()
	{
		return this.zone;
	}
	
	/**
	 * Set the zone of this call.
	 * 
	 * @param zone the zone to set.
     * @pre. zone is not null.
	 */
	public void setZone(CallZone zone)
	{
		this.zone = zone;
	}
	
	/**
	 * Get the minutes of this call.
	 * 
	 * @return the minutes of this call.
	 */
	public int getMinutes()
	{
		return this.minutes;
	}
	/**
	 * Set the number of minutes of this call.
	 * 
	 * @param minutes the number of minutes to set
	 * @pre. minutes is positive.
	 */
	public void setMinutes(int minutes)
	{
		assert minutes > 0;
		this.minutes = minutes;
	}
	
	/**
	 * Creates a string representation of the object.
	 * The string includes the number, call zone, and 
	 * number of minutes of the call. For example,
	 * "call to number +14167362100 in zone CANDA for 12 minutes".
	 * 
	 * @return the string representation of the object.
	 */
	@Override 
	public String toString()
	{
		return "call to number " + this.getNumber() + " in zone " + this.getZone() + " for " + this.getMinutes() + " minutes";
	}

	/**
	 * Creates a hash code for the object. 
	 * The hash code is generated by considering the call's number, call zone, and number of minutes.
	 * 
	 * @return the object's hash code.
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + minutes;
		result = prime * result + ((number == null) ? 0 : number.hashCode());
		result = prime * result + ((zone == null) ? 0 : zone.hashCode());
		return result;
	}
	
	/**
	 * Indicates whether some other object is "equal to" this one.
	 * The result is true if and only if the argument is not null, is a call,
	 * and both objects have the same number, call zone, and number of minutes.
	 * 
	 * @param obj the object to compare with.
	 * @return true if the calls' number, call zone,  and number of minutes are equal; false otherwise.
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Call other = (Call) obj;
		if (minutes != other.minutes)
			return false;
		if (number == null) {
			if (other.number != null)
				return false;
		} else if (!number.equals(other.number))
			return false;
		if (zone == null) {
			if (other.zone != null)
				return false;
		} else if (!zone.equals(other.zone))
			return false;
		return true;
	}
}
